# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 85a7ecf0398f7f7b26fb48793a9c385da990ba531b7a331829b96f0c2e4b21fbc5fef19ce6f5bad52046b11376e52ffe62a14cd2dd01e20c310fcde71f79c20e

test:
  secret_key_base: e85327cdabce608b3f9de44e4d3f7295a94a472660cb29086a9da44d7962c1aeba951310afba2bb27080510d6559530b6ef99d55a0c135fa6fbdb14fcf70fe0a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
